l_english:
 SETTINGS_PAGE_GRAPHICS:0 "Графіка"
 SETTINGS_PAGE_GAME:0 "Гра"
 SETTINGS_PAGE_SYSTEM:0 "система"
 SETTINGS_PAGE_CONTROLS:0 "Елементи управління"
 SETTINGS_PAGE_EDITOR:0 "Редактор"
 SETTINGS_PAGE_INTERFACE:0 "Інтерфейс"
 SETTINGS_PAGE_AUDIO:0 "Аудіо"
 SETTINGS_CATEGORY_SCREEN:0 "Екран"
 SETTINGS_CATEGORY_QUALITY:0 "Якість"
 OPTION_EASY:0 "Легко"
 OPTION_NORMAL:0 "Нормальний"
 OPTION_HARD:0 "Важко"
 OPTION_NEVER:0 "Ніколи"
 OPTION_MONTHLY:0 "Щомісяця"
 OPTION_HALFYEAR:0 "Кожні півроку"
 OPTION_YEARLY:0 "Щороку"
 OPTION_FIVE_YEAR:0 "Кожні п'ять років"
 OPTION_NO_AUTOSAVE:0 "Не зберігайте автоматично"
 SETTINGS_CATEGORY_ACCOUNT:0 "Обліковий запис"
 SETTINGS_CATEGORY_SYSTEM:0 "Система"
 SETTINGS_CATEGORY_CONTROLS:0 "Елементи управління"
 SETTINGS_CATEGORY_CAMERA:0 "Камера"
 SETTINGS_CATEGORY_AUDIO:0 "Аудіо"
 SETTINGS_CATEGORY_GUI:0 "GUI"
 SETTINGS_CATEGORY_INPUT_BINDINGS:0 "Прив’язки вводу"
 DISCARD:0 "Відкинути"
 SAVE_AND_CLOSE:0 "OK"
 SETTINGS:0 "Налаштування"
 REQUIRES_RESTART:0 "Вимагає перезавантаження"
 REQUIRE_RESTART_DESCRIPTION:0 "Деякі налаштування не набудуть чинності, доки ви не перезапустите гру."
 SETTINGS_INPUT_REMAP_INPUT:0 "Remap input"
 SETTINGS_INPUT_CONFIRM:0 "Підтвердити"
 SETTINGS_INPUT_CANCEL:0 "Скасувати"
 SETTINGS_INPUT_CLEAR:0 "Ясно"
 SETTINGS_INPUT_SAVE_INPUT_PROFILE:0 "Зберегти профіль"
 SETTINGS_INPUT_LOAD_INPUT_PROFILE:0 "Завантажити профіль"
 SETTINGS_INPUT_RESET_INPUT_PROFILE:0 "Скинути до значень за замовчуванням"
 SETTINGS_INPUT_BINDING_TEXT:0 "Будь ласка, виберіть прив’язку введення для дії '$INPUT_ACTION$':\n\n$INPUT_NAME$"
 SETTINGS_INPUT_BINDING_WARNING_TEXT:0 "Попередження: це прив’язування введення вже існує для '$INPUT_ACTION$'!\nПресування '$SETTINGS_INPUT_CONFIRM$' очистить стару прив'язку"
